word = input()
word = word.replace("c=", "c")
word = word.replace("c-", "c")
word = word.replace("dz=", "d")
word = word.replace("d-", "d")
word = word.replace("lj", "l")
word = word.replace("nj", "n")
word = word.replace("s=", "s")
word = word.replace("z=", "z")
word_list = list(word)
print(len(word_list))